# Production values for Asset Service

image:
  repository: gcr.io/YOUR_PROJECT_ID/asset-svc  # UPDATE THIS
  tag: v1.0.0
  pullPolicy: IfNotPresent

replicaCount: 2  # High availability

service:
  type: ClusterIP
  port: 3003

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

secrets:
  existingSecret: asset-svc-secrets

env:
  NODE_ENV: "production"
  PORT: "3003"
  LOG_LEVEL: "info"

