replicaCount: 2

image:
  repository: ticket-svc
  pullPolicy: Never
  tag: "v1"

service:
  type: ClusterIP
  port: 3002

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  NODE_ENV: production
  PORT: "3002"

secrets:
  databaseUrl: ""
  jwtSecret: ""
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  awsRegion: "us-east-1"
  s3BucketName: "saas-its-ticket-attachments"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

