apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        - name: NODE_ENV
          value: {{ .Values.env.NODE_ENV | quote }}
        - name: PORT
          value: {{ .Values.env.PORT | quote }}
        # - name: REDIS_URL
        #   value: "redis://redis:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ticket-svc-secrets
              key: databaseUrl
        - name: SHADOW_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ticket-svc-secrets
              key: databaseUrl
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ticket-svc-secrets
              key: jwtSecret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ticket-svc-secrets
              key: awsAccessKeyId
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ticket-svc-secrets
              key: awsSecretAccessKey
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: ticket-svc-secrets
              key: awsRegion
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: ticket-svc-secrets
              key: s3BucketName
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /v1/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5

